version: '3'
services:
  db:
    image: postgres
    env_file: .env
  web:
    build:
      context: ./backend
      dockerfile: /Dockerfile
    command: bash -c "rails db:create; rails db:migrate; rails s -p 80 -b 'web'"
    volumes:
      - ./backend:/web
    ports:
      - "80:80"
    depends_on:
      - db
    env_file: .env
