version: '3'
services:
  db:
    image: mysql
  web:
    build:
      context: .
      dockerfile: /backend/config/containers/web/Dockerfile
    volumes:
      - .:/backend/web
    ports:
      - "80:80"
    depends_on:
      - db
