FROM ruby:2.4.2
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /backend/web
WORKDIR /backend/web
ADD Gemfile /backend/web/Gemfile
ADD Gemfile.lock /backend/web/Gemfile.lock
RUN bundle install
ADD . /backend/web
